-- 코드를 입력하세요
SELECT CAR_ID, 
    CASE
        WHEN EXISTS (
            SELECT 1 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R
            WHERE R.CAR_ID = C.CAR_ID
                AND R.START_DATE <= '2022-10-16'AND R.END_DATE >= '2022-10-16'
    ) THEN '대여중' ELSE '대여 가능'
    END AS STATUS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;