-- 코드를 입력하세요
SELECT T.MONTH, T.CAR_ID, T.RECORDS
FROM (
    SELECT 
        MONTH(C.START_DATE) AS MONTH,
        C.CAR_ID,
        COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    WHERE YEAR(C.START_DATE) = 2022
      AND MONTH(C.START_DATE) BETWEEN 8 AND 10
    GROUP BY C.CAR_ID, MONTH(C.START_DATE)
) T
WHERE T.CAR_ID IN (
    SELECT C2.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C2
    WHERE YEAR(C2.START_DATE) = 2022
      AND MONTH(C2.START_DATE) BETWEEN 8 AND 10
    GROUP BY C2.CAR_ID
    HAVING COUNT(*) >= 5
)
ORDER BY T.MONTH, T.CAR_ID DESC; 
